package view;

import static covid19stats.Covid19Stats.mainForm;

//Η φόρμα με τις αρχικές επιλογές
public class MainForm extends javax.swing.JFrame {
    
    //constructor βασικής φόρμας
    public MainForm() {
        initComponents();
        //Προσθήκη κειμένου στα πλήκτρα της φόρμας
        jButton1.setText("Διαχείριση δεδομένων Covid19");
        jButton2.setText("Προβολή δεδομένων Covid19 ανά χώρα");
        jButton3.setText("Προβολή δεδομένων Covid19 σε χάρτη");
        jButton4.setText("Έξοδος");   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jButton1)
                .addGap(21, 21, 21)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Πάτημα πλήκτρου "Διαχείριση δεδομένων Covid19"
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Απόκρυψη της βασικής φόρμας
        mainForm.setVisible(false);
        //Δημιουργία της φόρμας manageDBForm
        ManageDBForm manageDBForm = new ManageDBForm();
        manageDBForm.setTitle("Διαχείριση δεδομένων Covid19");
        //Κεντράρισμα της φόρμας και εμφάνιση 
        manageDBForm.setLocationRelativeTo(null);
        manageDBForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    //Πάτημα πλήκτρου "Προβολή δεδομένων Covid19 ανά χώρα"
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Απόκρυψη της βασικής φόρμας
        mainForm.setVisible(false);
        //Δημιουργία της φόρμας countryDataForm
        CountryDataForm countryDataForm = new CountryDataForm();
        countryDataForm.setTitle("Προβολή δεδομένων Covid19 ανά χώρα");
        //Κεντράρισμα της φόρμας και εμφάνιση 
        countryDataForm.setLocationRelativeTo(null);
        countryDataForm.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    //Πάτημα πλήκτρου "Προβολή δεδομένων Covid19 σε χάρτη"
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       //Απόκρυψη της βασικής φόρμας
        mainForm.setVisible(false);
        //Δημιουργία της φόρμας googleMapForm
        GoogleMapForm googleMapForm = new GoogleMapForm();
        googleMapForm.setTitle("Προβολή δεδομένων Covid19 σε χάρτη");
        //Κεντράρισμα της φόρμας και εμφάνιση
        googleMapForm.setLocationRelativeTo(null);
        googleMapForm.setVisible(true);    
    }//GEN-LAST:event_jButton3ActionPerformed

    //Πάτημα πλήκτρου "Έξοδος"  
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Έξοδος από το πρόγραμμα
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
